FORMAT: 1A
HOST: http://localhost:8080

# Book API

## Books [/books]

### Get all books [GET]

+ Response 200 (application/json)

        [
          {
            "id": "BK-2302",
            "title": "API Design Patterns",
            "author": "J.J. Geewax",
            "publishedYear": 2021
          }
        ]

### Create a book [POST]

+ Request (application/json)

        {
          "title": "Clean Code",
          "author": "Robert C. Martin",
          "publishedYear": 2008
        }

+ Response 201 (application/json)

        {
          "id": "BK-0003",
          "title": "Clean Code",
          "author": "Robert C. Martin",
          "publishedYear": 2008
        }

---

## Book [/books/{id}]

+ Parameters
    + id: BK-2302 (string) - ID of the book

### Get book [GET]

+ Response 200 (application/json)

        {
          "id": "BK-2302",
          "title": "API Design Patterns",
          "author": "J.J. Geewax",
          "publishedYear": 2021
        }

### Update book [PUT]

+ Request (application/json)

        {
          "title": "Updated Title"
        }

+ Response 200 (application/json)

        {
          "id": "BK-2302",
          "title": "Updated Title",
          "author": "J.J. Geewax",
          "publishedYear": 2021
        }

### Delete book [DELETE]

+ Response 204