FORMAT: 1A
HOST: http://localhost:8080

# Book API

## Books [/books]

### Get all books [GET]
+ Response 200 (application/json)

### Create a book [POST]
+ Response 201

## Book [/books/{id}]

### Get book [GET]
+ Response 200

### Update book [PUT]
+ Response 200

### Delete book [DELETE]
+ Response 204