"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Book Management API",
    author="Team 6",
    author_email="dev_team_6@soa.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Book Management API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
