from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.author import Author
from openapi_server.models.pagination_meta import PaginationMeta
from openapi_server import util

from openapi_server.models.author import Author  # noqa: E501
from openapi_server.models.pagination_meta import PaginationMeta  # noqa: E501

class AuthorListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, meta=None):  # noqa: E501
        """AuthorListResponse - a model defined in OpenAPI

        :param data: The data of this AuthorListResponse.  # noqa: E501
        :type data: List[Author]
        :param meta: The meta of this AuthorListResponse.  # noqa: E501
        :type meta: PaginationMeta
        """
        self.openapi_types = {
            'data': List[Author],
            'meta': PaginationMeta
        }

        self.attribute_map = {
            'data': 'data',
            'meta': 'meta'
        }

        self._data = data
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'AuthorListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthorListResponse of this AuthorListResponse.  # noqa: E501
        :rtype: AuthorListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Author]:
        """Gets the data of this AuthorListResponse.


        :return: The data of this AuthorListResponse.
        :rtype: List[Author]
        """
        return self._data

    @data.setter
    def data(self, data: List[Author]):
        """Sets the data of this AuthorListResponse.


        :param data: The data of this AuthorListResponse.
        :type data: List[Author]
        """

        self._data = data

    @property
    def meta(self) -> PaginationMeta:
        """Gets the meta of this AuthorListResponse.


        :return: The meta of this AuthorListResponse.
        :rtype: PaginationMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: PaginationMeta):
        """Sets the meta of this AuthorListResponse.


        :param meta: The meta of this AuthorListResponse.
        :type meta: PaginationMeta
        """

        self._meta = meta
