from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_token=None, token_type=None, expires_in=None):  # noqa: E501
        """AuthResponse - a model defined in OpenAPI

        :param access_token: The access_token of this AuthResponse.  # noqa: E501
        :type access_token: str
        :param token_type: The token_type of this AuthResponse.  # noqa: E501
        :type token_type: str
        :param expires_in: The expires_in of this AuthResponse.  # noqa: E501
        :type expires_in: int
        """
        self.openapi_types = {
            'access_token': str,
            'token_type': str,
            'expires_in': int
        }

        self.attribute_map = {
            'access_token': 'accessToken',
            'token_type': 'tokenType',
            'expires_in': 'expiresIn'
        }

        self._access_token = access_token
        self._token_type = token_type
        self._expires_in = expires_in

    @classmethod
    def from_dict(cls, dikt) -> 'AuthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthResponse of this AuthResponse.  # noqa: E501
        :rtype: AuthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this AuthResponse.


        :return: The access_token of this AuthResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this AuthResponse.


        :param access_token: The access_token of this AuthResponse.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this AuthResponse.


        :return: The token_type of this AuthResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this AuthResponse.


        :param token_type: The token_type of this AuthResponse.
        :type token_type: str
        """

        self._token_type = token_type

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this AuthResponse.

        Token expiration time in seconds  # noqa: E501

        :return: The expires_in of this AuthResponse.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this AuthResponse.

        Token expiration time in seconds  # noqa: E501

        :param expires_in: The expires_in of this AuthResponse.
        :type expires_in: int
        """

        self._expires_in = expires_in
