from datetime import date, datetime  # noqa: F401
from uuid import UUID  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Author(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, biography=None, birth_date=None):  # noqa: E501
        """Author - a model defined in OpenAPI

        :param id: The id of this Author.  # noqa: E501
        :type id: UUID
        :param name: The name of this Author.  # noqa: E501
        :type name: str
        :param biography: The biography of this Author.  # noqa: E501
        :type biography: str
        :param birth_date: The birth_date of this Author.  # noqa: E501
        :type birth_date: date
        """
        self.openapi_types = {
            'id': UUID,
            'name': str,
            'biography': str,
            'birth_date': date
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'biography': 'biography',
            'birth_date': 'birthDate'
        }

        self._id = id
        self._name = name
        self._biography = biography
        self._birth_date = birth_date

    @classmethod
    def from_dict(cls, dikt) -> 'Author':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Author of this Author.  # noqa: E501
        :rtype: Author
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> UUID:
        """Gets the id of this Author.


        :return: The id of this Author.
        :rtype: UUID
        """
        return self._id

    @id.setter
    def id(self, id: UUID):
        """Sets the id of this Author.


        :param id: The id of this Author.
        :type id: UUID
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Author.


        :return: The name of this Author.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Author.


        :param name: The name of this Author.
        :type name: str
        """

        self._name = name

    @property
    def biography(self) -> str:
        """Gets the biography of this Author.


        :return: The biography of this Author.
        :rtype: str
        """
        return self._biography

    @biography.setter
    def biography(self, biography: str):
        """Sets the biography of this Author.


        :param biography: The biography of this Author.
        :type biography: str
        """

        self._biography = biography

    @property
    def birth_date(self) -> date:
        """Gets the birth_date of this Author.


        :return: The birth_date of this Author.
        :rtype: date
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date: date):
        """Sets the birth_date of this Author.


        :param birth_date: The birth_date of this Author.
        :type birth_date: date
        """

        self._birth_date = birth_date
