from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthorRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, biography=None, birth_date=None):  # noqa: E501
        """AuthorRequest - a model defined in OpenAPI

        :param name: The name of this AuthorRequest.  # noqa: E501
        :type name: str
        :param biography: The biography of this AuthorRequest.  # noqa: E501
        :type biography: str
        :param birth_date: The birth_date of this AuthorRequest.  # noqa: E501
        :type birth_date: date
        """
        self.openapi_types = {
            'name': str,
            'biography': str,
            'birth_date': date
        }

        self.attribute_map = {
            'name': 'name',
            'biography': 'biography',
            'birth_date': 'birthDate'
        }

        self._name = name
        self._biography = biography
        self._birth_date = birth_date

    @classmethod
    def from_dict(cls, dikt) -> 'AuthorRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthorRequest of this AuthorRequest.  # noqa: E501
        :rtype: AuthorRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AuthorRequest.


        :return: The name of this AuthorRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AuthorRequest.


        :param name: The name of this AuthorRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if name is not None and len(name) < 2:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `2`")  # noqa: E501

        self._name = name

    @property
    def biography(self) -> str:
        """Gets the biography of this AuthorRequest.


        :return: The biography of this AuthorRequest.
        :rtype: str
        """
        return self._biography

    @biography.setter
    def biography(self, biography: str):
        """Sets the biography of this AuthorRequest.


        :param biography: The biography of this AuthorRequest.
        :type biography: str
        """
        if biography is not None and len(biography) > 2000:
            raise ValueError("Invalid value for `biography`, length must be less than or equal to `2000`")  # noqa: E501

        self._biography = biography

    @property
    def birth_date(self) -> date:
        """Gets the birth_date of this AuthorRequest.


        :return: The birth_date of this AuthorRequest.
        :rtype: date
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date: date):
        """Sets the birth_date of this AuthorRequest.


        :param birth_date: The birth_date of this AuthorRequest.
        :type birth_date: date
        """

        self._birth_date = birth_date
