from datetime import date, datetime  # noqa: F401
from uuid import UUID  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, isbn=None, price=None, publish_date=None, author_id=None, category_id=None):  # noqa: E501
        """BookRequest - a model defined in OpenAPI

        :param title: The title of this BookRequest.  # noqa: E501
        :type title: str
        :param isbn: The isbn of this BookRequest.  # noqa: E501
        :type isbn: str
        :param price: The price of this BookRequest.  # noqa: E501
        :type price: float
        :param publish_date: The publish_date of this BookRequest.  # noqa: E501
        :type publish_date: date
        :param author_id: The author_id of this BookRequest.  # noqa: E501
        :type author_id: UUID
        :param category_id: The category_id of this BookRequest.  # noqa: E501
        :type category_id: UUID
        """
        self.openapi_types = {
            'title': str,
            'isbn': str,
            'price': float,
            'publish_date': date,
            'author_id': UUID,
            'category_id': UUID
        }

        self.attribute_map = {
            'title': 'title',
            'isbn': 'isbn',
            'price': 'price',
            'publish_date': 'publishDate',
            'author_id': 'authorId',
            'category_id': 'categoryId'
        }

        self._title = title
        self._isbn = isbn
        self._price = price
        self._publish_date = publish_date
        self._author_id = author_id
        self._category_id = category_id

    @classmethod
    def from_dict(cls, dikt) -> 'BookRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookRequest of this BookRequest.  # noqa: E501
        :rtype: BookRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookRequest.


        :return: The title of this BookRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookRequest.


        :param title: The title of this BookRequest.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 255:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `255`")  # noqa: E501
        if title is not None and len(title) < 1:
            raise ValueError("Invalid value for `title`, length must be greater than or equal to `1`")  # noqa: E501

        self._title = title

    @property
    def isbn(self) -> str:
        """Gets the isbn of this BookRequest.


        :return: The isbn of this BookRequest.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this BookRequest.


        :param isbn: The isbn of this BookRequest.
        :type isbn: str
        """
        if isbn is None:
            raise ValueError("Invalid value for `isbn`, must not be `None`")  # noqa: E501
        if isbn is not None and len(isbn) > 13:
            raise ValueError("Invalid value for `isbn`, length must be less than or equal to `13`")  # noqa: E501
        if isbn is not None and len(isbn) < 10:
            raise ValueError("Invalid value for `isbn`, length must be greater than or equal to `10`")  # noqa: E501

        self._isbn = isbn

    @property
    def price(self) -> float:
        """Gets the price of this BookRequest.


        :return: The price of this BookRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this BookRequest.


        :param price: The price of this BookRequest.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501
        if price is not None and price < 0:  # noqa: E501
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `0`")  # noqa: E501

        self._price = price

    @property
    def publish_date(self) -> date:
        """Gets the publish_date of this BookRequest.


        :return: The publish_date of this BookRequest.
        :rtype: date
        """
        return self._publish_date

    @publish_date.setter
    def publish_date(self, publish_date: date):
        """Sets the publish_date of this BookRequest.


        :param publish_date: The publish_date of this BookRequest.
        :type publish_date: date
        """

        self._publish_date = publish_date

    @property
    def author_id(self) -> UUID:
        """Gets the author_id of this BookRequest.


        :return: The author_id of this BookRequest.
        :rtype: UUID
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id: UUID):
        """Sets the author_id of this BookRequest.


        :param author_id: The author_id of this BookRequest.
        :type author_id: UUID
        """
        if author_id is None:
            raise ValueError("Invalid value for `author_id`, must not be `None`")  # noqa: E501

        self._author_id = author_id

    @property
    def category_id(self) -> UUID:
        """Gets the category_id of this BookRequest.


        :return: The category_id of this BookRequest.
        :rtype: UUID
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id: UUID):
        """Sets the category_id of this BookRequest.


        :param category_id: The category_id of this BookRequest.
        :type category_id: UUID
        """
        if category_id is None:
            raise ValueError("Invalid value for `category_id`, must not be `None`")  # noqa: E501

        self._category_id = category_id
