from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Book(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, isbn=None, price=None, publish_date=None, author_id=None, category_id=None, created_at=None, updated_at=None):  # noqa: E501
        """Book - a model defined in OpenAPI

        :param id: The id of this Book.  # noqa: E501
        :type id: UUID
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param isbn: The isbn of this Book.  # noqa: E501
        :type isbn: str
        :param price: The price of this Book.  # noqa: E501
        :type price: float
        :param publish_date: The publish_date of this Book.  # noqa: E501
        :type publish_date: date
        :param author_id: The author_id of this Book.  # noqa: E501
        :type author_id: UUID
        :param category_id: The category_id of this Book.  # noqa: E501
        :type category_id: UUID
        :param created_at: The created_at of this Book.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Book.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': UUID,
            'title': str,
            'isbn': str,
            'price': float,
            'publish_date': date,
            'author_id': UUID,
            'category_id': UUID,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'isbn': 'isbn',
            'price': 'price',
            'publish_date': 'publishDate',
            'author_id': 'authorId',
            'category_id': 'categoryId',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._title = title
        self._isbn = isbn
        self._price = price
        self._publish_date = publish_date
        self._author_id = author_id
        self._category_id = category_id
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> UUID:
        """Gets the id of this Book.


        :return: The id of this Book.
        :rtype: UUID
        """
        return self._id

    @id.setter
    def id(self, id: UUID):
        """Sets the id of this Book.


        :param id: The id of this Book.
        :type id: UUID
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.


        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.


        :param title: The title of this Book.
        :type title: str
        """

        self._title = title

    @property
    def isbn(self) -> str:
        """Gets the isbn of this Book.


        :return: The isbn of this Book.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this Book.


        :param isbn: The isbn of this Book.
        :type isbn: str
        """

        self._isbn = isbn

    @property
    def price(self) -> float:
        """Gets the price of this Book.


        :return: The price of this Book.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Book.


        :param price: The price of this Book.
        :type price: float
        """

        self._price = price

    @property
    def publish_date(self) -> date:
        """Gets the publish_date of this Book.


        :return: The publish_date of this Book.
        :rtype: date
        """
        return self._publish_date

    @publish_date.setter
    def publish_date(self, publish_date: date):
        """Sets the publish_date of this Book.


        :param publish_date: The publish_date of this Book.
        :type publish_date: date
        """

        self._publish_date = publish_date

    @property
    def author_id(self) -> UUID:
        """Gets the author_id of this Book.


        :return: The author_id of this Book.
        :rtype: UUID
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id: UUID):
        """Sets the author_id of this Book.


        :param author_id: The author_id of this Book.
        :type author_id: UUID
        """

        self._author_id = author_id

    @property
    def category_id(self) -> UUID:
        """Gets the category_id of this Book.


        :return: The category_id of this Book.
        :rtype: UUID
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id: UUID):
        """Sets the category_id of this Book.


        :param category_id: The category_id of this Book.
        :type category_id: UUID
        """

        self._category_id = category_id

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Book.


        :return: The created_at of this Book.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Book.


        :param created_at: The created_at of this Book.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Book.


        :return: The updated_at of this Book.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Book.


        :param updated_at: The updated_at of this Book.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
