from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PaginationMeta(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total_items=None, item_count=None, items_per_page=None, total_pages=None, current_page=None):  # noqa: E501
        """PaginationMeta - a model defined in OpenAPI

        :param total_items: The total_items of this PaginationMeta.  # noqa: E501
        :type total_items: int
        :param item_count: The item_count of this PaginationMeta.  # noqa: E501
        :type item_count: int
        :param items_per_page: The items_per_page of this PaginationMeta.  # noqa: E501
        :type items_per_page: int
        :param total_pages: The total_pages of this PaginationMeta.  # noqa: E501
        :type total_pages: int
        :param current_page: The current_page of this PaginationMeta.  # noqa: E501
        :type current_page: int
        """
        self.openapi_types = {
            'total_items': int,
            'item_count': int,
            'items_per_page': int,
            'total_pages': int,
            'current_page': int
        }

        self.attribute_map = {
            'total_items': 'totalItems',
            'item_count': 'itemCount',
            'items_per_page': 'itemsPerPage',
            'total_pages': 'totalPages',
            'current_page': 'currentPage'
        }

        self._total_items = total_items
        self._item_count = item_count
        self._items_per_page = items_per_page
        self._total_pages = total_pages
        self._current_page = current_page

    @classmethod
    def from_dict(cls, dikt) -> 'PaginationMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginationMeta of this PaginationMeta.  # noqa: E501
        :rtype: PaginationMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_items(self) -> int:
        """Gets the total_items of this PaginationMeta.


        :return: The total_items of this PaginationMeta.
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items: int):
        """Sets the total_items of this PaginationMeta.


        :param total_items: The total_items of this PaginationMeta.
        :type total_items: int
        """

        self._total_items = total_items

    @property
    def item_count(self) -> int:
        """Gets the item_count of this PaginationMeta.


        :return: The item_count of this PaginationMeta.
        :rtype: int
        """
        return self._item_count

    @item_count.setter
    def item_count(self, item_count: int):
        """Sets the item_count of this PaginationMeta.


        :param item_count: The item_count of this PaginationMeta.
        :type item_count: int
        """

        self._item_count = item_count

    @property
    def items_per_page(self) -> int:
        """Gets the items_per_page of this PaginationMeta.


        :return: The items_per_page of this PaginationMeta.
        :rtype: int
        """
        return self._items_per_page

    @items_per_page.setter
    def items_per_page(self, items_per_page: int):
        """Sets the items_per_page of this PaginationMeta.


        :param items_per_page: The items_per_page of this PaginationMeta.
        :type items_per_page: int
        """

        self._items_per_page = items_per_page

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this PaginationMeta.


        :return: The total_pages of this PaginationMeta.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this PaginationMeta.


        :param total_pages: The total_pages of this PaginationMeta.
        :type total_pages: int
        """

        self._total_pages = total_pages

    @property
    def current_page(self) -> int:
        """Gets the current_page of this PaginationMeta.


        :return: The current_page of this PaginationMeta.
        :rtype: int
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page: int):
        """Sets the current_page of this PaginationMeta.


        :param current_page: The current_page of this PaginationMeta.
        :type current_page: int
        """

        self._current_page = current_page
