# coding: utf-8

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_request import BookRequest

class TestBookRequest(unittest.TestCase):
    """BookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookRequest:
        """Test BookRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookRequest`
        """
        model = BookRequest()
        if include_optional:
            return BookRequest(
                title = 'Clean Code',
                isbn = '9780132350884',
                price = 45.99,
                publish_date = 'Fri Aug 01 07:00:00 ICT 2008',
                author_id = '550e8400-e29b-41d4-a716-446655440000',
                category_id = '550e8400-e29b-41d4-a716-446655440001'
            )
        else:
            return BookRequest(
                title = 'Clean Code',
                isbn = '9780132350884',
                price = 45.99,
                author_id = '550e8400-e29b-41d4-a716-446655440000',
                category_id = '550e8400-e29b-41d4-a716-446655440001',
        )
        """

    def testBookRequest(self):
        """Test BookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
