# coding: utf-8

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authors_api import AuthorsApi


class TestAuthorsApi(unittest.TestCase):
    """AuthorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_author(self) -> None:
        """Test case for create_author

        Create a new author
        """
        pass

    def test_get_authors(self) -> None:
        """Test case for get_authors

        Get all authors
        """
        pass


if __name__ == '__main__':
    unittest.main()
