# coding: utf-8

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_list_response import BookListResponse

class TestBookListResponse(unittest.TestCase):
    """BookListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookListResponse:
        """Test BookListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookListResponse`
        """
        model = BookListResponse()
        if include_optional:
            return BookListResponse(
                data = [
                    openapi_client.models.book.Book(
                        id = '123e4567-e89b-12d3-a456-426614174000', 
                        title = 'Clean Code', 
                        isbn = '978-0132350884', 
                        price = 45.99, 
                        publish_date = 'Fri Aug 01 07:00:00 ICT 2008', 
                        author_id = '', 
                        category_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = openapi_client.models.pagination_meta.PaginationMeta(
                    total_items = 150, 
                    item_count = 10, 
                    items_per_page = 10, 
                    total_pages = 15, 
                    current_page = 1, )
            )
        else:
            return BookListResponse(
        )
        """

    def testBookListResponse(self):
        """Test BookListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
