# coding: utf-8

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pagination_meta import PaginationMeta

class TestPaginationMeta(unittest.TestCase):
    """PaginationMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationMeta:
        """Test PaginationMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationMeta`
        """
        model = PaginationMeta()
        if include_optional:
            return PaginationMeta(
                total_items = 150,
                item_count = 10,
                items_per_page = 10,
                total_pages = 15,
                current_page = 1
            )
        else:
            return PaginationMeta(
        )
        """

    def testPaginationMeta(self):
        """Test PaginationMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
