# coding: utf-8

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.author_list_response import AuthorListResponse

class TestAuthorListResponse(unittest.TestCase):
    """AuthorListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorListResponse:
        """Test AuthorListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorListResponse`
        """
        model = AuthorListResponse()
        if include_optional:
            return AuthorListResponse(
                data = [
                    openapi_client.models.author.Author(
                        id = '', 
                        name = 'Robert C. Martin', 
                        biography = 'Uncle Bob is a software engineer...', 
                        birth_date = 'Fri Dec 05 08:00:00 ICT 1952', )
                    ],
                meta = openapi_client.models.pagination_meta.PaginationMeta(
                    total_items = 150, 
                    item_count = 10, 
                    items_per_page = 10, 
                    total_pages = 15, 
                    current_page = 1, )
            )
        else:
            return AuthorListResponse(
        )
        """

    def testAuthorListResponse(self):
        """Test AuthorListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
