# coding: utf-8

"""
    Book Management API

    A simple CRUD API for managing a library, designed for the SOA course.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book import Book

class TestBook(unittest.TestCase):
    """Book unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Book:
        """Test Book
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Book`
        """
        model = Book()
        if include_optional:
            return Book(
                id = 'BK-2302',
                title = 'API Design Patterns',
                author = 'J.J. Geewax',
                published_year = 2021
            )
        else:
            return Book(
                title = 'API Design Patterns',
                author = 'J.J. Geewax',
        )
        """

    def testBook(self):
        """Test Book"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
