# coding: utf-8

# flake8: noqa

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthApi",
    "AuthorsApi",
    "BooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthResponse",
    "Author",
    "AuthorListResponse",
    "AuthorRequest",
    "Book",
    "BookListResponse",
    "BookRequest",
    "Error",
    "LoginRequest",
    "PaginationMeta",
]

# import apis into sdk package
from openapi_client.api.auth_api import AuthApi as AuthApi
from openapi_client.api.authors_api import AuthorsApi as AuthorsApi
from openapi_client.api.books_api import BooksApi as BooksApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.auth_response import AuthResponse as AuthResponse
from openapi_client.models.author import Author as Author
from openapi_client.models.author_list_response import AuthorListResponse as AuthorListResponse
from openapi_client.models.author_request import AuthorRequest as AuthorRequest
from openapi_client.models.book import Book as Book
from openapi_client.models.book_list_response import BookListResponse as BookListResponse
from openapi_client.models.book_request import BookRequest as BookRequest
from openapi_client.models.error import Error as Error
from openapi_client.models.login_request import LoginRequest as LoginRequest
from openapi_client.models.pagination_meta import PaginationMeta as PaginationMeta

