# coding: utf-8

# flake8: noqa
"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.auth_response import AuthResponse
from openapi_client.models.author import Author
from openapi_client.models.author_list_response import AuthorListResponse
from openapi_client.models.author_request import AuthorRequest
from openapi_client.models.book import Book
from openapi_client.models.book_list_response import BookListResponse
from openapi_client.models.book_request import BookRequest
from openapi_client.models.error import Error
from openapi_client.models.login_request import LoginRequest
from openapi_client.models.pagination_meta import PaginationMeta

