# coding: utf-8

"""
    Book Management API

    RESTful API for the Book Management application. Supports managing Books, Authors, Categories, and User Authentication (JWT). This documentation is highly detailed and structurally optimized for automatic backend code generation (Spring Boot, NestJS, Go, Python, etc.).

    The version of the OpenAPI document: 1.0.0
    Contact: dev_team_6@soa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AuthResponse(BaseModel):
    """
    AuthResponse
    """ # noqa: E501
    access_token: Optional[StrictStr] = Field(default=None, alias="accessToken")
    token_type: Optional[StrictStr] = Field(default=None, alias="tokenType")
    expires_in: Optional[StrictInt] = Field(default=None, description="Token expiration time in seconds", alias="expiresIn")
    __properties: ClassVar[List[str]] = ["accessToken", "tokenType", "expiresIn"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessToken": obj.get("accessToken"),
            "tokenType": obj.get("tokenType"),
            "expiresIn": obj.get("expiresIn")
        })
        return _obj


